-- MySQL Script generated by MySQL Workbench
-- Sat Jun  3 23:19:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema friend_man
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friend_man
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friend_man` DEFAULT CHARACTER SET utf8mb3 ;
USE `friend_man` ;

-- -----------------------------------------------------
-- Table `friend_man`.`animals_reestr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friend_man`.`animals_reestr` (
  `Id` INT NOT NULL,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `Vid` VARCHAR(45) NULL DEFAULT NULL,
  `Eating` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_animals_reestr_young_animals`
    FOREIGN KEY (`Id`)
    REFERENCES `friend_man`.`young_animals` (`IdReestr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animals_reestr_pack_animals1`
    FOREIGN KEY (`Id`)
    REFERENCES `friend_man`.`pack_animals` (`idReestr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animals_reestr_homesanimals1`
    FOREIGN KEY (`Id`)
    REFERENCES `friend_man`.`homesanimals` (`idReestr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `Id_UNIQUE` ON `friend_man`.`animals_reestr` (`Id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `friend_man`.`homesanimals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friend_man`.`homesanimals` (
  `idReestr` INT NOT NULL,
  `HomeName` VARCHAR(45) NULL DEFAULT NULL,
  `Comands` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `friend_man`.`pack_animals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friend_man`.`pack_animals` (
  `idReestr` INT NOT NULL,
  `Weight` INT NULL DEFAULT NULL,
  `Description` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `friend_man`.`young_animals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friend_man`.`young_animals` (
  `IdReestr` INT NOT NULL,
  `ages` VARCHAR(8) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `friend_man`.`animals_reestr`
-- -----------------------------------------------------
START TRANSACTION;
USE `friend_man`;
INSERT INTO `friend_man`.`animals_reestr` (`Id`, `Date`, `Vid`, `Eating`) VALUES (1, '09.07.2021', 'Собака', 'Сухой корм');
INSERT INTO `friend_man`.`animals_reestr` (`Id`, `Date`, `Vid`, `Eating`) VALUES (2, '18.04.2009', 'Осёл', 'Овёс');
INSERT INTO `friend_man`.`animals_reestr` (`Id`, `Date`, `Vid`, `Eating`) VALUES (3, '12.05.2018', 'Ворона', 'Семечки');
INSERT INTO `friend_man`.`animals_reestr` (`Id`, `Date`, `Vid`, `Eating`) VALUES (4, '05.05.2022', 'Лошадь', 'Овёс');

COMMIT;


-- -----------------------------------------------------
-- Data for table `friend_man`.`homesanimals`
-- -----------------------------------------------------
START TRANSACTION;
USE `friend_man`;
INSERT INTO `friend_man`.`homesanimals` (`idReestr`, `HomeName`, `Comands`) VALUES (1, 'Собакен', 'none');
INSERT INTO `friend_man`.`homesanimals` (`idReestr`, `HomeName`, `Comands`) VALUES (3, 'Сорока', 'none');

COMMIT;


-- -----------------------------------------------------
-- Data for table `friend_man`.`pack_animals`
-- -----------------------------------------------------
START TRANSACTION;
USE `friend_man`;
INSERT INTO `friend_man`.`pack_animals` (`idReestr`, `Weight`, `Description`) VALUES (2, 120, 'none');
INSERT INTO `friend_man`.`pack_animals` (`idReestr`, `Weight`, `Description`) VALUES (4, 110, 'none');

COMMIT;


-- -----------------------------------------------------
-- Data for table `friend_man`.`young_animals`
-- -----------------------------------------------------
START TRANSACTION;
USE `friend_man`;
INSERT INTO `friend_man`.`young_animals` (`IdReestr`, `ages`) VALUES (4, '01.00.29');

COMMIT;

